### ISSUE TITLE
Where tf do you get the VM to run this thing?

### ISSUE THREAD

**Issue by backfromhiatus** [Tukeque/URCL-OS#1]
See title

**Comment by backfromhiatus** [comment]
RUN RAM, not RUN ROM
Bc my OS is RUN RAM and Im to retarded to make one so, yeah. Thanks!

**Comment by Tukeque** [comment]
@Verlio-H give this guy an answer

**Comment by backfromhiatus** [comment]
Yeah

**Comment by Verlio-H** [comment]
URCL-OS does not require a vm to run, it can run in urcx found at https://bramotte.github.io/urcl-explorer/, the RUN RAM header is from back when DW only existed in RUN RAM systems, if you need to find a VM for one of your projects, I recommend you check the #urcl-vm channel in the discord and scroll up a ways and there are some github links.

**Comment by backfromhiatus** [comment]
Ok thnx
